---
groups:
- name: {{app_name}}
  jobs:
  - prepare-cf-dev
  - code-scan-dev
  - prepare-cf-test
  - smoke-test
  - publish

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: git-develop
  type: git
  source:
    branch: develop
    uri: {{git_uri}}
    private_key: {{git_private_key}}
    skip_ssl_verification: true

- name: git-test
  type: git
  source:
    branch: test
    uri: {{git_uri}}
    private_key: {{git_private_key}}
    skip_ssl_verification: true

- name: git-uat
  type: git
  source:
    branch: uat
    uri: {{git_uri}}
    private_key: {{git_private_key}}
    skip_ssl_verification: true


- name: cf-push-dev
  type: cf
  source:
    api: "https://api.sys.cac.preview.pcf.manulife.com"
    username: {{pcf_dev_user}}
    password: {{pcf_dev_pass}}
    organization: {{dev_org}}
    space:  {{dev_space}}
    skip_cert_check: true

- name: cf-push-test
  type: cf
  source:
    api: "https://api.sys.cac.preview.pcf.manulife.com"
    username: {{pcf_dev_user}}
    password: {{pcf_dev_pass}}
    organization: {{test_org}}
    space:  {{test_space}}
    skip_cert_check: true

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

jobs:

- name: prepare-cf-dev
  serial: true
  public: true
  plan:
  - aggregate:
    - get: gitfolder
      resource: git-develop
      trigger: true
  - put: slack-alert
    params:
      channel: 'pipeline_msg'
      username: concourse
      icon_emoji: ':simple_smile:'
      always-notify: true
      text: |
        {{app_name}} - $BUILD_JOB_NAME has started.
  - task: unit-test
    file: gitfolder/concourse/uat_prod/unit-test.yml
    params:
        TERM: xterm
        NPM_REGISTRY: {{npm_registry}}
        NPM_AUTH: {{npm_auth}}
        NPM_EMAIL: {{npm_email}}
        NPM_SASS_BINARY_SITE: {{npm_sass_binary_site}}
    on_failure:
      put: slack-alert
      params:
        always-notify: true
        channel: '#pipeline_msg'
        icon_emoji: ':disappointed:'
        text: |
          {{app_name}} - job $BUILD_JOB_NAME, unit-test has FAILED
  - task: assemble
    file: gitfolder/concourse/uat_prod/assemble.yml
    params:
        TERM: xterm
        NPM_REGISTRY: {{npm_registry}}
        NPM_AUTH: {{npm_auth}}
        NPM_EMAIL: {{npm_email}}
        NPM_SASS_BINARY_SITE: {{npm_sass_binary_site}}
    on_failure:
      put: slack-alert
      params:
        always-notify: true
        channel: '#pipeline_msg'
        icon_emoji: ':disappointed:'
        text: |
          {{app_name}} - job $BUILD_JOB_NAME, assemble has FAILED

  - task: assemble-services
    file: gitfolder/concourse/uat_prod/assemble-services.yml
    params:
      TERM: xterm
      PCF_API: "https://api.sys.cac.preview.pcf.manulife.com"
      PCF_USER: {{pcf_dev_user}}
      PCF_PASSWORD: {{pcf_dev_pass}}
      PCF_ORG: {{dev_org}}
      PCF_SPACE: {{dev_space}}

  - put: cf-push-dev
    on_failure:
        put: slack-alert
        params:
          username: concourse
          channel: '#pipeline_msg'
          icon_emoji: ':disappointed:'
          always-notify: true
          text: |
            {{app_name}} - $BUILD_JOB_NAME, cf-push-dev has FAILED.
    on_success:
        put: slack-alert
        params:
          username: concourse
          always-notify: true
          channel: '#pipeline_msg'
          icon_emoji: ':heavy_check_mark:'
          text: |
            {{app_name}} - $BUILD_JOB_NAME, cf-push-dev has succeeded!    
    params:
      manifest: target/manifest-dev.yml
      path: target

  - put: git-test
    params: {repository: gitfolder}

- name: prepare-cf-test
  serial: true
  public: true
  plan:
  - aggregate:
    - get: gitfolder
      resource: git-test
      trigger: false
  - put: slack-alert
    params:
      channel: '#pipeline_msg'
      icon_emoji: ':simple_smile:'      
      text: |
        {{app_name}} - $BUILD_JOB_NAME has started. "\n"
  - task: assemble
    file: gitfolder/concourse/uat_prod/assemble.yml
    params:
        TERM: xterm
        NPM_REGISTRY: {{npm_registry}}
        NPM_AUTH: {{npm_auth}}
        NPM_EMAIL: {{npm_email}}
        NPM_SASS_BINARY_SITE: {{npm_sass_binary_site}}
    on_failure:
      put: slack-alert
      params:
        always-notify: true
        channel: '#pipeline_msg'
        icon_emoji: ':disappointed:'
        text: |
          {{app_name}} - job $BUILD_JOB_NAME, assemble has FAILED
  - task: assemble-services
    file: gitfolder/concourse/uat_prod/assemble-services.yml
    params:
      TERM: xterm
      PCF_API: "https://api.sys.cac.preview.pcf.manulife.com"
      PCF_USER: {{pcf_dev_user}}
      PCF_PASSWORD: {{pcf_dev_pass}}
      PCF_ORG: {{test_org}}
      PCF_SPACE: {{test_space}}
    on_failure:
      put: slack-alert
      params:
        always-notify: true
        channel: '#pipeline_msg'
        icon_emoji: ':disappointed:'
        text: |
          {{app_name}} - job $BUILD_JOB_NAME, assemble-services has FAILED
  - put: cf-push-test
    params:
      manifest: target/manifest-test.yml
      path: target
    on_failure:
      put: slack-alert
      params:
        always-notify: true
        channel: '#pipeline_msg'
        icon_emoji: ':disappointed:'
        text: |
          {{app_name}} - job $BUILD_JOB_NAME, cf-push-test has FAILED
  - put: git-uat
    params: {repository: gitfolder}

- name: code-scan-dev
  serial: true
  public: true
  plan:
  - aggregate:
    - get: gitfolder
      trigger: true
      resource: git-develop
  - task: code-scan
    file: gitfolder/concourse/uat_prod/code-scan.yml
    params:
        TERM: xterm

- name: smoke-test
  serial: true
  public: true
  plan:
  - aggregate:
    - get: gitfolder
      resource: git-uat
      trigger: true
      passed: [prepare-cf-test]
  - task: smoke-test
    file: gitfolder/concourse/uat_prod/smoke-test.yml
    params:
        TERM: xterm
        NPM_REGISTRY: {{npm_registry}}
        NPM_AUTH: {{npm_auth}}
        NPM_EMAIL: {{npm_email}}
        NPM_SASS_BINARY_SITE: {{npm_sass_binary_site}}

- name: publish
  serial: true
  public: true
  plan:
  - aggregate:
    - get: gitfolder
      resource: git-uat
      passed: [smoke-test]
      trigger: true
  - task: publish
    file: gitfolder/concourse/uat_prod/publish.yml
    params:
      TERM: xterm
